# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

use_frameworks! :linkage => :static

target 'mobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # RNMapbox iOS integration hooks (replace deprecated setup.rb)
  pre_install do |installer|
    if defined?($RNMapboxMaps) && $RNMapboxMaps.respond_to?(:pre_install)
      $RNMapboxMaps.pre_install(installer)
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Enforce iOS 15.1 minimum for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end

    if defined?($RNMapboxMaps) && $RNMapboxMaps.respond_to?(:post_install)
      $RNMapboxMaps.post_install(installer)
    end
  end
end
